### ISSUE TITLE
Reproduce SEAL on Cora,Citeseer,Pubmed

### ISSUE THREAD

**Issue by Xi-yuanWang** [melifluos/subgraph-sketching#14]
Thanks for sharing the code. I am reproducing the link prediction performances of SEAL on Cora, Citeseer, and Pubmed. However, using the official code in https://github.com/facebookresearch/SEAL_OGB produces a far lower score than that reported in this paper. Could you please provides some details on how to reproduce SEAL?

**Comment by Barcavin** [comment]
I believe in this work, the authors use the validation edges as input when evaluating the test edges. It is detailed in the paper appendix B.2. This may cause the performance much better compared to the one without use_val_as_input.

**Comment by Xi-yuanWang** [comment]
Thank you for the helpful suggestion. But I still cannot reproduce the SEAL results in this paper with use_val_as_input.

**Comment by lei-liu1** [comment]
Possibly because they use the largest connected component (lcc) on the Planetoid datasets, the source code is as follows:

![image](https://github.com/melifluos/subgraph-sketching/assets/57094098/ee22c497-24d2-4205-a8da-f57df493d8f3)

**Comment by yanhlai4bio** [comment]
The same problem also troubles me now. I run this code following the instructions in Readme. However, my reproduced results are much lower than those presented in the published paper. Would you happen to have any progress and give me some advice?

**Comment by melifluos** [comment]
@yanhlai4bio this is because we lost access to the optimal hyperparameters (and the entire codebase) when Elon Musk took over at Twitter and had to try to reproduce it from memory. We lacked the resources to exactly reproduce the hyperparameter sweep, but I have since updated the instructions (at least for the OGB datasets) that should reproduce the results in the paper.
