### ISSUE TITLE
reproduce the results of GCN and SAGE on Planetoid

### ISSUE THREAD

**Issue by dingfangyu** [melifluos/subgraph-sketching#5]
Thanks for providing the code, but how to reproduce the link prediction performances of GNN baselines on Planetoid?

**Comment by shir994** [comment]
You can find the models [here](https://github.com/melifluos/subgraph-sketching/blob/main/src/models/gnn.py)
Due to all the events at Twitter this is not an original repository we used for an actual work. At the moment, the SAGE and GCN baseline running commands and/or model selection in the `run.py` file are missing. We might add them with the corresponding hyperparameters to the repository later.

**Comment by dingfangyu** [comment]
Thanks!
